<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // const myPromise = new Promise((resolve, reject) => {
      //   if (2 + 2 === 5) resolve("resolved");
      //   reject("rejected");
      // });
      // myPromise
      //   .then((res) => console.log(res))
      //   .catch((err) => console.log(err));

      //EXAMPLE 2 - CONSUMING WITH .THEN
      // const myPromise = new Promise(async (resolve, reject) => {
      //   try {
      //     const response = await fetch("https://api.kanye.rest/");
      //     const json = await response.json();
      //     resolve(json.quote);
      //   } catch (error) {
      //     reject("rejected");
      //   }
      // });

      // myPromise
      //   .then((res) => console.log(res))
      //   .catch((err) => console.log(err));

      //EXAMPLE 3 - CONSUMING WITH ASYNC AWAIT
      const returnPromise = () => {
        return new Promise(async (resolve, reject) => {
          try {
            const response = await fetch("https://api.kanye.rest/");
            const json = await response.json();
            resolve(json.quote);
          } catch (error) {
            reject("lol u r the bot- what happends to you");
          }
        });
      };

      const consumePromise = async () => {
        try {
          const result = await returnPromise();
          console.log(result);
        } catch (error) {
          console.log(error);
        }
      };
      //WHENEVER YOU USE ASYNC AWAIT TO CONSUME PROMISES YOU HAVE TO USE TRY CATCH BLOCKS
      consumePromise();
    </script>
  </body>
</html>
